-- CRIANDO BANCO DE DADOS
CREATE DATABASE Pizzaria;
-- USANDO BANCO DE DADOS
USE Pizzaria;
-- TABELA CLIENTES
CREATE TABLE Clientes (
ClienteID INT PRIMARY KEY AUTO_INCREMENT,
Nome VARCHAR (100),
Endereco VARCHAR (255),
Telefone VARCHAR(15)
);
-- TABELA PEDIDOS
CREATE TABLE Pedidos(
PedidoID INT PRIMARY KEY AUTO_INCREMENT,
ClienteID INT,
DataHorarioPedido DATETIME,
ValorTotal DECIMAL(10,2),
FOREIGN KEY (ClienteID) REFERENCES Clientes(CLienteID)
);
-- TABELA ITENSPEDIDOS
CREATE TABLE ItensPedidos(
ItemPedidoID INT PRIMARY KEY AUTO_INCREMENT,
PedidoID INT,
PizzaID INT,
Quantidade INT,
FOREIGN KEY (PedidoID) REFERENCES Pedidos(PedidoID),
FOREIGN KEY (PizzaID) REFERENCES Pizzas(PizzaID)
);
-- TABELA PIZZAS
CREATE TABLE Pizzas(
PizzaID INT PRIMARY KEY AUTO_INCREMENT,
Nome VARCHAR(100),
Massa VARCHAR(50),
Borda VARCHAR(50),
Preco DECIMAL (10,2)
);
-- TABELA BEBIDAS
CREATE TABLE BEBIDAS(
BebidaID INT PRIMARY KEY AUTO_INCREMENT,
Descricao VARCHAR(100),
Preco DECIMAL (10,2)
);
-- TABELA INGREDIENTES
CREATE TABLE Ingredientes(
IngredienteID INT PRIMARY KEY AUTO_INCREMENT,
Nome VARCHAR(100)
);
-- TABELA INGREDIENTES POR PIZZA
CREATE TABLE IngredientesPorPizza(
RelacaoID INT PRIMARY KEY AUTO_INCREMENT,
PizzaID INT,
IngredienteID INT,
FOREIGN KEY (PizzaID) REFERENCES Pizzas(PizzaID),
FOREIGN KEY (IngredienteID) REFERENCES Ingredientes(IngredienteID)
);
-- TABELA BORDAS
CREATE TABLE BORDAS(
BordaID INT PRIMARY KEY,
NomeBorda VARCHAR(100),
PizzaID INT,
FOREIGN KEY (PizzaID) REFERENCES Pizzas(PizzaID)
);
-- TABELA MASSAS
CREATE TABLE MASSAS(
MassaID INT PRIMARY KEY,
NomeMassa VARCHAR(100),
PizzaID INT,
FOREIGN KEY (PizzaID) REFERENCES Pizzas(PizzaID)
);
-- TABELA FORNADASPIZZAS
CREATE TABLE FornadasPizzas(
FornadaID INT PRIMARY KEY AUTO_INCREMENT,
PedidoID INT,
DataHoraFornada DATETIME,
QuantidadeProduzida INT,
StatusPizza VARCHAR (50),
FOREIGN KEY (PedidoID) REFERENCES Pedidos(PedidoID)
);